apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app1-deployment
  labels:
    app: nodejs-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app1
  template:
    metadata:
      labels:
        app: nodejs-app1
    spec:
      containers:
      - name: nodejs-app1
        image: <ECR_URI>:latest
        ports:
        - containerPort: 3000
